### ISSUE TITLE
Installing on Alloy site seems to break drag and drop

### ISSUE THREAD

**Issue by davidknipe** [ITMeric/ITMeric.ImageCrop#1]
Tried installing this on a new Alloy site and when adding the properties to the start page as follows:

public class StartPage : SitePageData
{
    [ImageReference(CropRatio = 1d, AllowedTypes = new[] { typeof(ImageFile) })]
    public virtual ImageReference SingleImageReference { get; set; }

    [ImageReference(CropRatio = 1d, AllowedTypes = new[] { typeof(ImageFile) })]
    public virtual ImageReferenceList ImageReferenceList { get; set; }
    //...
}

It seems to break the drag and drop functionality in the UI. I tried dragging an image from the media widget to the start page.

**Comment by maciejgolis** [comment]
Hi David,

Thanks for reaching out.

As per my email to you guys, I wanted to submit the updated version, but for some reason I don't to seem have sufficient permissions to log in to nuget.episerver.com any more.

What would be the best way to provide the updated version?

Thank you.
M

**Comment by davidknipe** [comment]
I will delete your original file and see if it allows you to re-upload

**Comment by maciejgolis** [comment]
Would the that I have uploaded a package stop me from logging in? (I tried resetting my password etc)

**Comment by davidknipe** [comment]
It shouldn't stop you logging in. The username is the some one as used on world.episerver.com - can you check if you can log in there?

**Comment by davidknipe** [comment]
Worth dropping a mail to epw@episerver.com to see if they can work out what the issue is

**Comment by maciejgolis** [comment]
Hi David,

Long time no speak!

Despite a number of email to epw I never heard back. Would you mind helping out?

Thanks, M

**Comment by maciejgolis** [comment]
Latest package is ready for the review - I used my private account to upload the package. 

Look forward to hearing back from you.

M

**Comment by davidknipe** [comment]
Tested and working in a default Alloy site. Now available on the Episerver Nuget feed: 
[(https://nuget.episerver.com/package/?id=ITMeric.ImageCrop)]
